"""empty message

Revision ID: 2a014df060dd
Revises: d3962f00ae8e
Create Date: 2021-03-02 01:20:52.947648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a014df060dd'
down_revision = 'd3962f00ae8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=True),
    sa.Column('path', sa.Unicode(length=128), nullable=True),
    sa.Column('type', sa.Unicode(length=3), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('feedback', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('post', sa.Column('path', sa.Unicode(length=128), nullable=True))
    op.add_column('post', sa.Column('short_description', sa.Text(), nullable=True))
    op.add_column('xoz', sa.Column('code_gran', sa.Integer(), nullable=True))
    op.add_column('xoz', sa.Column('code_humus', sa.Integer(), nullable=True))
    op.add_column('xoz', sa.Column('code_ph', sa.Integer(), nullable=True))
    op.add_column('xoz', sa.Column('code_salinisation', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('xoz', 'code_salinisation')
    op.drop_column('xoz', 'code_ph')
    op.drop_column('xoz', 'code_humus')
    op.drop_column('xoz', 'code_gran')
    op.drop_column('post', 'short_description')
    op.drop_column('post', 'path')
    op.drop_column('feedback', 'date')
    op.drop_table('storage')
    # ### end Alembic commands ###
