"""empty message

Revision ID: 6b5ad35b67f1
Revises: 2a014df060dd
Create Date: 2021-03-02 01:26:55.293357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b5ad35b67f1'
down_revision = '2a014df060dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('type', sa.Unicode(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'type')
    # ### end Alembic commands ###
