"""empty message

Revision ID: 920f16cd54a4
Revises: 6b5ad35b67f1
Create Date: 2021-03-02 01:38:27.990240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920f16cd54a4'
down_revision = '6b5ad35b67f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('path', sa.VARCHAR(length=128), nullable=True),
    sa.Column('type', sa.VARCHAR(length=3), nullable=True),
    sa.Column('create_date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
