"""empty message

Revision ID: a3277509761e
Revises: 4d8e5c6183a8
Create Date: 2021-02-24 18:53:10.991516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3277509761e'
down_revision = '4d8e5c6183a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('email', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'email')
    # ### end Alembic commands ###
