"""empty message

Revision ID: cdf9774be86e
Revises: a3277509761e
Create Date: 2021-02-24 23:15:08.036868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf9774be86e'
down_revision = 'a3277509761e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tablenso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_tip', sa.Integer(), nullable=True),
    sa.Column('index_tip', sa.String(length=10), nullable=True),
    sa.Column('name_tip_podtip', sa.String(length=100), nullable=True),
    sa.Column('granulometry', sa.Integer(), nullable=True),
    sa.Column('power', sa.Integer(), nullable=True),
    sa.Column('humus_1', sa.Integer(), nullable=True),
    sa.Column('humus_2', sa.String(length=10), nullable=True),
    sa.Column('ph_water1', sa.Integer(), nullable=True),
    sa.Column('ph_water2', sa.String(length=10), nullable=True),
    sa.Column('water_sm', sa.Integer(), nullable=True),
    sa.Column('water_mm', sa.String(length=10), nullable=True),
    sa.Column('ground_water', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tablenso')
    # ### end Alembic commands ###
