"""empty message

Revision ID: d3962f00ae8e
Revises: cdf9774be86e
Create Date: 2021-02-25 00:04:40.265979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3962f00ae8e'
down_revision = 'cdf9774be86e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aggregates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('gradation', sa.Text(), nullable=True),
    sa.Column('criterion', sa.String(length=50), nullable=True),
    sa.Column('id_tip', sa.String(length=50), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bulkweight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('gradation', sa.Text(), nullable=True),
    sa.Column('criterion', sa.Text(), nullable=True),
    sa.Column('id_tip', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deflation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('gradation', sa.Text(), nullable=True),
    sa.Column('criterion', sa.Text(), nullable=True),
    sa.Column('id_tip', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('erosion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('gradation', sa.Text(), nullable=True),
    sa.Column('criterion', sa.Text(), nullable=True),
    sa.Column('id_tip', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('granulometry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('gradation', sa.Text(), nullable=True),
    sa.Column('criterion', sa.Text(), nullable=True),
    sa.Column('id_tip', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('humus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('gradation', sa.Text(), nullable=True),
    sa.Column('criterion', sa.Text(), nullable=True),
    sa.Column('id_tip', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moisture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('gradation', sa.Text(), nullable=True),
    sa.Column('criterion', sa.Text(), nullable=True),
    sa.Column('id_tip', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ph',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('gradation', sa.Text(), nullable=True),
    sa.Column('criterion_1', sa.Text(), nullable=True),
    sa.Column('criterion_2', sa.Text(), nullable=True),
    sa.Column('id_tip', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phosphorus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('gradation', sa.Text(), nullable=True),
    sa.Column('criterion', sa.Text(), nullable=True),
    sa.Column('id_tip', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('potassium',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('gradation', sa.Text(), nullable=True),
    sa.Column('criterion', sa.Text(), nullable=True),
    sa.Column('id_tip', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('power',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('gradation', sa.Text(), nullable=True),
    sa.Column('criterion', sa.Text(), nullable=True),
    sa.Column('id_tip', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salinization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('gradation', sa.Text(), nullable=True),
    sa.Column('criterion_1', sa.Text(), nullable=True),
    sa.Column('criterion_2', sa.Text(), nullable=True),
    sa.Column('criterion_3', sa.Text(), nullable=True),
    sa.Column('criterion_4', sa.Text(), nullable=True),
    sa.Column('id_tip', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solonetzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('gradation', sa.Text(), nullable=True),
    sa.Column('criterion', sa.Text(), nullable=True),
    sa.Column('id_tip', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('water_resistant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('gradation', sa.Text(), nullable=True),
    sa.Column('criterion', sa.Text(), nullable=True),
    sa.Column('id_tip', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xoz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_type', sa.Integer(), nullable=True),
    sa.Column('id_soil', sa.Integer(), nullable=True),
    sa.Column('podtype', sa.Text(), nullable=True),
    sa.Column('name_soil', sa.Text(), nullable=True),
    sa.Column('index_map', sa.Text(), nullable=True),
    sa.Column('index_base', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('raion', sa.Text(), nullable=True),
    sa.Column('power', sa.Integer(), nullable=True),
    sa.Column('humus', sa.Float(), nullable=True),
    sa.Column('clay', sa.Integer(), nullable=True),
    sa.Column('ph', sa.Float(), nullable=True),
    sa.Column('phoshorus', sa.Integer(), nullable=True),
    sa.Column('potassium', sa.Integer(), nullable=True),
    sa.Column('aggregates', sa.Integer(), nullable=True),
    sa.Column('bulkweight', sa.Float(), nullable=True),
    sa.Column('code_power', sa.Integer(), nullable=True),
    sa.Column('code_phoshorus', sa.Integer(), nullable=True),
    sa.Column('code_potassium', sa.Integer(), nullable=True),
    sa.Column('code_aggregates', sa.Integer(), nullable=True),
    sa.Column('code_bulkweight', sa.Integer(), nullable=True),
    sa.Column('code_erosia', sa.Integer(), nullable=True),
    sa.Column('code_solonetzes', sa.Integer(), nullable=True),
    sa.Column('code_drain', sa.Integer(), nullable=True),
    sa.Column('kpower', sa.Float(), nullable=True),
    sa.Column('khumus', sa.Float(), nullable=True),
    sa.Column('kclay', sa.Float(), nullable=True),
    sa.Column('kph', sa.Float(), nullable=True),
    sa.Column('kerosion', sa.Float(), nullable=True),
    sa.Column('ksolon', sa.Float(), nullable=True),
    sa.Column('ksalin', sa.Float(), nullable=True),
    sa.Column('kdrain', sa.Float(), nullable=True),
    sa.Column('ksoil', sa.Float(), nullable=True),
    sa.Column('bonitet', sa.Text(), nullable=True),
    sa.Column('pei', sa.Text(), nullable=True),
    sa.Column('standard_yield', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xoz')
    op.drop_table('water_resistant')
    op.drop_table('solonetzes')
    op.drop_table('salinization')
    op.drop_table('power')
    op.drop_table('potassium')
    op.drop_table('phosphorus')
    op.drop_table('ph')
    op.drop_table('moisture')
    op.drop_table('humus')
    op.drop_table('granulometry')
    op.drop_table('erosion')
    op.drop_table('deflation')
    op.drop_table('bulkweight')
    op.drop_table('aggregates')
    # ### end Alembic commands ###
